### ISSUE TITLE
Implement detailview/webview 

### ISSUE THREAD

**Issue by jaimeong** [Zihung/SteamQuery#2]
when user clicks on news article in news feed -> detail view fragment or possibly webview

**Comment by jaimeong** [comment]
we have access to the news article's url if we wanna do webview

**Comment by jmsato** [comment]
WebView works for external links. The page will not fully load if the link goes to the steam-community website.

**Comment by jaimeong** [comment]
Fixed the non-loading bug for steam-community
needed to set settings for web view
webView.getSettings().javaScriptEnabled = true;
webView.getSettings().domStorageEnabled = true;
